### ISSUE TITLE
Fails to build with rtaudio-6.0.0: error: no member named 'probed' in 'RtAudio::DeviceInfo'

### ISSUE THREAD

**Issue by yurivict** [muse-sequencer/muse#1235]
**Describe the bug**
```
/wrkdirs/usr/ports/audio/muse-sequencer/work/muse-4.1.0/src/muse/driver/rtaudio.cpp:225:13: error: no member named 'probed' in 'RtAudio::DeviceInfo'
  if(!in_di.probed || !out_di.probed)
      ~~~~~ ^
/wrkdirs/usr/ports/audio/muse-sequencer/work/muse-4.1.0/src/muse/driver/rtaudio.cpp:225:31: error: no member named 'probed' in 'RtAudio::DeviceInfo'
  if(!in_di.probed || !out_di.probed)
                       ~~~~~~ ^
/wrkdirs/usr/ports/audio/muse-sequencer/work/muse-4.1.0/src/muse/driver/rtaudio.cpp:326:13: error: unknown type name 'RtAudioError'; did you mean 'RtAudioErrorType'?
  } catch ( RtAudioError& e ) {
            ^~~~~~~~~~~~
            RtAudioErrorType
```

**To Reproduce**
regular build

**Desktop (please complete the following information):**
 - OS: FreeBSD 13.2

**Additional context**
Version: 4.1.0 (last released version)

**Comment by terminator356** [comment]
Hello again Yuri.
This was fixed a few days ago in github master, after someone filed an issue here:
[https://github.com/muse-sequencer/muse/issues/1233](url)

Try it if you can. Let me know if any trouble.

**Comment by yurivict** [comment]
> Try it if you can. Let me know if any trouble.

It builds fine now. I guess you should make a release now with this change to help other distros, because all of them would have the same problem.

**Comment by spamatica** [comment]
> I guess you should make a release now with this change to help other distros, because all of them would have the same problem.

Very good idea! It is high time :) ... probably some bugs we need to iron out tho..
